### ISSUE TITLE
KeyError: 'codet5p'

### ISSUE THREAD

**Issue by shailja-thakur** [salesforce/CodeT5#113]
Getting the following error on the transformers-4.30.0.dev0

Traceback (most recent call last):
  File "gen_examples_HDLProblems_CodeT5.py", line 60, in <module>
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
  File "/home/hp2265/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 398, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/hp2265/.local/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 421, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'codet5p'

**Comment by yuewang-cuhk** [comment]
Hi, can you provide a minimal example to reproduce the error? Besides, you can try to use the same version of `transformers-4.21.3`.
